data("iris")
classs(iris)
print("viewing head and tail of iris dataset")
head(iris)
tail(iris)
print("summary of iris dataset")
summary(iris)
print("No of rows adn columns")
nrow(iris)
ncol(iris)
print("display colnames")
colnames(iris)
print("creating a histogram")
hist(iris$Sepal.Length,main="Sepal Length",xlab="sepals",col="yellow",border="black")
plot(iris$Sepal.Length,iris$Sepal.Width,main="Sepal Length vs Sepal Width",xlab="Sepal Length",ylab="Sepal Width",col="blue")
boxplot(iris$Sepal,Width~iris$Sepal.Length,main="Boxplot of Sepal Length by width",xlab="Sepal Length",ylab="Sepal Width",col="red")